delete from chargeback_category;

insert into chargeback_category(id, title) values(1, 'стягнення коштів');
insert into chargeback_category(id, title) values(2, 'звернення стягнення на майно');
insert into chargeback_category(id, title) values(3, 'стягнення аліментів');
insert into chargeback_category(id, title) values(4, 'стягнення періодичних платежів (крім аліментів)');
insert into chargeback_category(id, title) values(5, 'стягнення заборгованості із заробітної плати та інших платежів, пов’язаних з трудовими відносинами');
insert into chargeback_category(id, title) values(6, 'стягнення соціальних виплат');
insert into chargeback_category(id, title) values(7, 'стягнення заборгованості з оплати комунальних послуг');
insert into chargeback_category(id, title) values(8, 'стягнення штрафів у справах про адміністративні правопорушення');
insert into chargeback_category(id, title) values(9, 'стягнення штрафів у справах про адміністративні правопорушення у сфері безпеки дорожнього руху');
insert into chargeback_category(id, title) values(10, 'забезпечення позову');
insert into chargeback_category(id, title) values(11, 'зобов’язання вчинити певні дії або утриматися від їх вчинення<');
insert into chargeback_category(id, title) values(12, 'поновлення на роботі');
insert into chargeback_category(id, title) values(13, 'вселення стягувача');
insert into chargeback_category(id, title) values(14, 'виселення');
insert into chargeback_category(id, title) values(15, 'відібрання дитини');
insert into chargeback_category(id, title) values(16, 'заборона вчиняти певні дії');
insert into chargeback_category(id, title) values(17, 'конфіскація майна');
insert into chargeback_category(id, title) values(18, 'конфіскація майна, вилученого митними органами');
insert into chargeback_category(id, title) values(19, 'конфіскація майна засуджених');
insert into chargeback_category(id, title) values(20, 'конфіскація коштів та майна за вчинення корупційного та пов’язаного з корупцією правопорушення');
insert into chargeback_category(id, title) values(21, 'оплатне вилучення');
insert into chargeback_category(id, title) values(22, 'передача стягувачу предметів, зазначених у виконавчому документі');
insert into chargeback_category(id, title) values(23, 'стягнення коштів на користь держави');
insert into chargeback_category(id, title) values(24, 'рішення Європейського суду з прав людини');
insert into chargeback_category(id, title) values(25, 'стягнення виконавчого збору');
insert into chargeback_category(id, title) values(26, 'стягнення витрат виконавчого провадження');
insert into chargeback_category(id, title) values(27, 'стягнення штрафів, накладених державним, приватним виконавцем');
insert into chargeback_category(id, title) values(28, 'стягнення основної винагороди приватного виконавця');
insert into chargeback_category(id, title) values(29, 'усунення перешкод у побаченні з дитиною, встановлення побачення з дитиною');